In [9]:
from sklearn import datasets
digits = datasets.load_digits()

from ucimlrepo import fetch_ucirepo

# fetch dataset
wine = fetch_ucirepo(id=109)

# data (as pandas dataframes)
wine_data = wine.data.features
wine_target = wine.data.targets

In [10]:
from sklearn import tree
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

decision_tree = tree.DecisionTreeClassifier()
knn = KNeighborsClassifier()
naive_bayes = GaussianNB()

scaler = MinMaxScaler()
scaler.fit(wine_data)
wine_data_normalized = scaler.transform(wine_data)

wine_target = wine_target.to_numpy()


In [11]:
from sklearn import model_selection
import numpy as np
kf = model_selection.StratifiedKFold(n_splits=3)

predicted_classes = dict()
predicted_classes['tree'] = np.zeros(wine_target.shape[0])
predicted_classes['knn'] = np.zeros(wine_target.shape[0])
predicted_classes['naive'] = np.zeros(wine_target.shape[0])

wine_data

,Alcohol,Malicacid,Ash,Alcalinity_of_ash,Magnesium,Total_phenols,Flavanoids,Nonflavanoid_phenols,Proanthocyanins,Color_intensity,Hue,0D280_0D315_of_diluted_wines,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840


In [14]:
for train,test in kf.split(wine_data_normalized,wine_target):
    print(train)
    print(test)

[ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115
 116 117 118 119 120 121 122 123 124 125 126 127 128 129 146 147 148 149
 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167
 168 169 170 171 172 173 174 175 176 177]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74
  75  76  77  78  79  80  81  82 130 131 132 133 134 135 136 137 138 139
 140 141 142 143 144 145]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82 106 107 108 109 110

In [24]:
for train,test in kf.split(wine_data,wine_target):
    data_train,target_train = wine_data_normalized[train],wine_target[train]
    data_test,target_test = wine_data_normalized[test],wine_target[test]

    decision_tree = decision_tree.fit(data_train,target_train)
    decision_tree_predicted = decision_tree.predict(data_test)
    predicted_classes['tree'][test] = decision_tree_predicted

    knn = knn.fit(data_train,target_train)
    knn_predicted = knn.predict(data_test)
    predicted_classes['knn'][test] = knn_predicted

    naive_bayes = naive_bayes.fit(data_train,target_train)
    naive_predicted = naive_bayes.predict(data_test)
    predicted_classes['naive'][test] = naive_predicted


C:\Users\lhuan\AppData\Roaming\Python\Python312\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\lhuan\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1310: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\lhuan\AppData\Roaming\Python\Python312\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\lhuan\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1310: DataConversionWarning: A column-vector y was passed

In [25]:
from sklearn import metrics

for classifier in predicted_classes.keys():
    print("==========================================================================================================================")
    print("Resultados do classificador %s\n%s\n" %(classifier,metrics.classification_report(wine_target,predicted_classes[classifier])))
    print("Matriz de confusao: \n%s\n\n\n" %metrics.confusion_matrix(wine_target,predicted_classes[classifier]))

Resultados do classificador tree
              precision    recall  f1-score   support

           1       0.93      0.86      0.89        59
           2       0.86      0.92      0.88        71
           3       0.96      0.94      0.95        48

    accuracy                           0.90       178
   macro avg       0.91      0.91      0.91       178
weighted avg       0.91      0.90      0.90       178


Matriz de confusao: 
[[51  8  0]
 [ 4 65  2]
 [ 0  3 45]]



Resultados do classificador knn
              precision    recall  f1-score   support

           1       0.94      1.00      0.97        59
           2       1.00      0.90      0.95        71
           3       0.94      1.00      0.97        48

    accuracy                           0.96       178
   macro avg       0.96      0.97      0.96       178
weighted avg       0.96      0.96      0.96       178


Matriz de confusao: 
[[59  0  0]
 [ 4 64  3]
 [ 0  0 48]]



Resultados do classificador naive
              p