In [1]:
from sklearn import datasets
from sklearn import datasets
digits = datasets.load_digits()

from ucimlrepo import fetch_ucirepo

# fetch dataset
wine = fetch_ucirepo(id=109)

# data (as pandas dataframes)
wine_data = wine.data.features
wine_target = wine.data.targets

digits = datasets.load_digits()

In [2]:
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.naive_bayes import GaussianNB

decision_tree = tree.DecisionTreeClassifier()
knn = KNeighborsClassifier()
naive_bayes = GaussianNB()

scaler = MinMaxScaler()
scaler.fit(wine_data)
wine_data_normalized = scaler.transform(wine_data)

wine_target_numpy = wine_target.to_numpy()



In [3]:
from sklearn import model_selection
import numpy as np
kf = model_selection.StratifiedKFold(n_splits=10)

predicted_classes = dict()
predicted_classes['tree'] = np.zeros(digits.target.shape[0])
predicted_classes['knn'] = np.zeros(digits.target.shape[0])
predicted_classes['naive'] = np.zeros(digits.target.shape[0])


In [4]:
for s in predicted_classes:
    print(predicted_classes[s])

[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]


In [5]:
for train,test in kf.split(digits.data,digits.target):
    data_train,target_train = digits.data[train],digits.target[train]
    data_test,target_test = digits.data[test],digits.target[test]

    decision_tree = decision_tree.fit(data_train,target_train)
    decision_tree_predicted = decision_tree.predict(data_test)
    predicted_classes['tree'][test] = decision_tree_predicted

    knn = knn.fit(data_train,target_train)
    knn_predicted = knn.predict(data_test)
    predicted_classes['knn'][test] = knn_predicted

    naive_bayes = naive_bayes.fit(data_train,target_train)
    naive_bayes_predicted = naive_bayes.predict(data_test)
    predicted_classes['naive'][test] = naive_bayes_predicted


In [6]:
for s in predicted_classes:
    print(predicted_classes[s])

[0. 1. 8. ... 8. 9. 8.]
[0. 1. 8. ... 8. 9. 8.]
[0. 1. 8. ... 8. 9. 8.]


In [18]:

from sklearn import metrics

for classifier in predicted_classes.keys():
    print("==========================================================================================================================")
    print("Resultados do classificador %s\n%s\n" %(classifier,metrics.classification_report(digits.target,predicted_classes[classifier])))
    print("Matriz de confusao: \n%s\n\n\n" %metrics.confusion_matrix(digits.target,predicted_classes[classifier]))

[0. 1. 8. ... 8. 9. 8.]
Resultados do classificador tree
              precision    recall  f1-score   support

           0       0.97      0.94      0.95       178
           1       0.78      0.79      0.78       182
           2       0.78      0.80      0.79       177
           3       0.78      0.77      0.77       183
           4       0.87      0.81      0.84       181
           5       0.87      0.88      0.87       182
           6       0.90      0.88      0.89       181
           7       0.82      0.83      0.83       179
           8       0.73      0.72      0.72       174
           9       0.77      0.85      0.81       180

    accuracy                           0.83      1797
   macro avg       0.83      0.83      0.83      1797
weighted avg       0.83      0.83      0.83      1797


Matriz de confusao: 
[[167   0   3   2   2   0   1   0   2   1]
 [  0 143  13   2   1   0   1   0   8  14]
 [  1   8 141   4   0   0   4   0  16   3]
 [  0   5   6 141   1  10   1   5